### ISSUE TITLE
error[E0599]: no method named `local_file` found for struct `proc_macro2::Span` in the current scope

### ISSUE THREAD

**Issue by h0lme3** [solana-foundation/anchor#3676]
I'm having a new trouble when I build anchor initial project today:

error[E0599]: no method named `local_file` found for struct `proc_macro2::Span` in the current scope
   --> /home/haodev007/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-syn-0.31.1/src/idl/defined.rs:501:22
    |
500 |                   let source_path = proc_macro2::Span::call_site()
    |  ___________________________________-
501 | |                     .local_file()
    | |                     -^^^^^^^^^^ method not found in `Span`
    | |_____________________|
    |

I've checked the issue https://github.com/solana-foundation/anchor/issues/3662 yesterday and downgraded proc-macro2 crate version
`cargo update -p proc-macro2 --precise 1.0.94`
It worked with anchor version `0.31.0` yesterday after downgraded `proc-macro2` version but it doesnt work again

current rust and anchor version is
`rustc 1.86.0 (05f9846f8 2025-03-31)`
`anchor-cli 0.31.1`

Please help me, thanks!

**Comment by jacobcreech** [comment]
@h0lme3 what's your Solana cli version as well?

Most people have fixed this issue by upgrading to latest rustc stable with anchor 0.31.1

**Comment by Sniger** [comment]
I’m experiencing the same issue, it worked yesterday but not today.

**Comment by h0lme3** [comment]
> [@h0lme3](https://github.com/h0lme3) what's your Solana cli version as well?
> 
> Most people have fixed this issue by upgrading to latest rustc stable with anchor 0.31.1

solana cli version
`solana-cli 2.1.19 (src:c696ac8f; feat:1416569292, client:Agave)`

**Comment by jacobcreech** [comment]
@h0lme3 could you run `cargo update`? Seems people are running into this because their crates.io cache is out of date.

**Comment by getong** [comment]
> [@h0lme3](https://github.com/h0lme3) could you run `cargo update`? Seems people are running into this because their crates.io cache is out of date.

`cargo update` not work
`anchor build --no-idl` works

**Comment by h0lme3** [comment]
> [@h0lme3](https://github.com/h0lme3) could you run `cargo update`? Seems people are running into this because their crates.io cache is out of date.

@jacobcreech sorry, it's just not working and `anchor build --no-idl` works to build project temporarily without idl.
But we should still do like that?

**Comment by DeepakMehra53** [comment]
> Current Version
   `rust version : rustc 1.86.0 (05f9846f8 2025-03-31) `
   `anchor version : anchor-cli 0.31.1 `
  `cargo version : cargo 1.86.0 (adf9b6ad1 2025-02-28) `
  `proc-macro : "1.0.94"`

> while build the anchor didn't work
   `anchor build  ❌`

> Issue
   `cannot find type `SourceFile` in crate `proc_macro` Compiler(proc_macro::SourceFile),`
🧩Likely caused by a dependency (possibly proc-macro2) attempting to access compiler-only APIs.
>Now should i downgrade the proc-macro2 crate

**Comment by jsonDoge** [comment]
Was only able to get it back working with IDL using these (Linux):
anchor: 0.31.0
rustc: 1.79.0
solana-cli: 2.1.0

proc-macro2: 1.0.95
+ the fix described here: https://solana.stackexchange.com/questions/21553/proc-macro2-issue

defined.rs 499 line replace with -> `let source_path = proc_macro2::Span::call_site().file();`

**Comment by dehypnosis** [comment]
Any folks found comprehensive solution while locking in 0.31.0 ?

**Comment by alloc33** [comment]
that's crazy how fragile is everything here lol

**Comment by alloc33** [comment]
`cargo update` fixed the stuff

**Comment by mikemaccana** [comment]
Have been getting the following since upgrading to 0.31.1 (yes point one).

```
Solana CLI: solana-cli 2.1.0 (src:c1080de4; feat:3176011155, client:Agave)
Anchor: anchor-cli 0.31.1
Node: v22.11.0
Rust: rustc 1.82.0 (f6e511eec 2024-10-15)
```

I have run `cargo update` as request.

When I run `anchor build` I get:

```
error[E0599]: no method named `file` found for reference `&proc_macro::Span` in the current scope
   --> /Users/mike/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.95/src/wrapper.rs:465:36
    |
465 |             Span::Compiler(s) => s.file(),
    |                                    ^^^^ method not found in `&Span`

error[E0599]: no method named `local_file` found for reference `&proc_macro::Span` in the current scope
   --> /Users/mike/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.95/src/wrapper.rs:473:36
    |
473 |             Span::Compiler(s) => s.local_file(),
    |                                    ^^^^^^^^^^ method not found in `&Span`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `proc-macro2` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Building IDL failed. Run `ANCHOR_LOG=true anchor idl build` to see the logs.
```

**Comment by adisehrawat** [comment]
Okay, try this
reinstall rust and anchor then check for the anchor version, it should be 0.31.1 then recreate the project and check for the anchor-lang version in cargo.toml and anchor_version in Anchor.toml, it should be 0.31.1 and then try anchor build. It works for me after new update of anchor

**Comment by rotcan** [comment]
@mikemaccana Did you find any solution? I am getting same error. 

rust - nightly-2025-04-21
anchor - 0.31.1
solana - 2.1.4
proc-macro2 - 0.1.94

**Comment by jacobcreech** [comment]
@rotcan Your issue is with `proc-macro2 1.0.94`. It needs to be at least `1.0.95`

**Comment by jacobcreech** [comment]
For those that are running into this issue, do the following:

1. `rustup update`
2. Remove your cargo.lock or confirm that `proc-macro2` is `1.0.95` or higher
3. `anchor build`

and you should complete successfully. The problem lies in you not having nightly 04-16 or higher locally, anchor 0.31.1, and proc-macro2 <1.0.95

**Comment by adisehrawat** [comment]
@rotcan do 
```
cargo update -p proc-macro2
```
this will update proc-macro2 to latest version 1.0.95

**Comment by adisehrawat** [comment]
@jacobcreech you are right man, I did same, updated that proc macro2 and issue solved

**Comment by h0lme3** [comment]
> For those that are running into this issue, do the following:
> 
> 1. `rustup update`
> 2. Remove your cargo.lock or confirm that `proc-macro2` is `1.0.95` or higher
> 3. `anchor build`
> 
> and you should complete successfully. The problem lies in you not having nightly 04-16 or higher locally, anchor 0.31.1, and proc-macro2 <1.0.95

Hey @jacobcreech anchor build works for me after upgrading nightly version - thanks!

**Comment by h0lme3** [comment]
I think we can close the issue - I just hope everyone can settle the problem via this issue in time. Big thanks to @jacobcreech !
